# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 이남형
tagline: 방송대 경제학과 조교수
description: >- # this means to ignore newlines until "baseurl:"
 방송통신대학교 경제학과 조교수 이남형
baseurl: "" # the subpath of your site, e.g. /blog
# url: https://namhyunglee.github.io # the base hostname & protocol for your site, e.g. http://example.com
url: https://www.namhyunglee.net
email: namhyunglee@knou.ac.kr

author:
  name: "이남형"
#  avatar: "/assets/images/bio-photo.jpg"
#  bio: "I am an **amazing** person." # Note: Markdown is allowed
#  location: "Somewhere"
#  links:
#    - label: "Made Mistakes"
#      icon: "fas fa-fw fa-link"
#      url: "https://mademistakes.com"
#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
#      url: "https://twitter.com/mmistakes"
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/mmistakes"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/mmistakes"

#footer:
#  links:
#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
#      url: "https://twitter.com/mmistakes"
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/mmistakes"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/mmistakes"

#theme: minimal-mistakes-jekyll
#remote_theme: pmarsceill/just-the-docs
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
encoding: UTF-8

#permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
#aux_links:
#  "Just the Docs on GitHub":
#    - "//github.com/pmarsceill/just-the-docs"

# Makes Aux links open in a new tab. Default is false
#aux_links_new_tab: true

# Sort order for navigation links
nav_sort: case_insensitive # default, equivalent to nil
# nav_sort: case_sensitive # Capital letters sorted before lowercase

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "상단으로 돌아가기"

footer_content: 
#"Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html



# Footer "Edit this page on GitHub" link text
#gh_edit_link: true # show or hide edit this page link
#gh_edit_link_text: "Edit this page on GitHub"
#gh_edit_repository: "https://github.com/pmarsceill/just-the-docs" # the github URL for your repo
#gh_edit_branch: "master" # the branch that your docs is served from
#gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-115799530-1"
    anonymize_ip: false # default
	
plugins:
#  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

defaults:
   # _posts
   - scope:
       path: ""
       type: posts
     values:
       layout: single
       read_time: true
       comments: true
       share: true
       related: true 

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
